import React, { useState } from 'react';
import { motion } from 'framer-motion';
import {
  Upload,
  FileCheck,
  Database,
  Brain,
  Lightbulb,
  CheckCircle2,
  ArrowRight,
  Sparkles
} from 'lucide-react';

export default function HowItWorks({ onGetStarted }) {
  const [activePipelineStep, setActivePipelineStep] = useState(0);

  const pipelineSteps = [
    {
      step: '01',
      title: 'Upload CSV / ERP Sync',
      icon: Upload,
      detail: 'Drag & drop Tally, Zoho, Excel registers, or connect direct PostgreSQL endpoints.',
      sampleData: 'Uploading sales_register_2026.csv (14.2 MB)...'
    },
    {
      step: '02',
      title: 'Validation Engine',
      icon: FileCheck,
      detail: 'Automatic schema normalization, deduplication, and anomaly scrubbing.',
      sampleData: 'Scrubbing 14,890 rows. 0 corrupted cells detected.'
    },
    {
      step: '03',
      title: 'PostgreSQL Enterprise DB',
      icon: Database,
      detail: 'Encrypted multi-tenant relational persistence with sub-millisecond query indexing.',
      sampleData: 'Indexed into PostgreSQL DB table: ledger_transactions'
    },
    {
      step: '04',
      title: 'AI Neural Analysis',
      icon: Brain,
      detail: 'Specialized LLM & statistical models calculate unit economics & cash runway.',
      sampleData: 'Evaluating Monte Carlo cashflow (90-day horizon)...'
    },
    {
      step: '05',
      title: 'Recommendations',
      icon: Lightbulb,
      detail: 'Strategic playbooks generated by AI CEO & AI CFO for instant executive review.',
      sampleData: 'Recommendation #409: Reorder SKU-809 to save $18,400.'
    },
    {
      step: '06',
      title: 'Business Actions',
      icon: CheckCircle2,
      detail: 'One-click execution of POs, payment reminders, and inventory re-allocations.',
      sampleData: 'Purchase order committed & vendor notification sent.'
    }
  ];

  return (
    <section id="how-it-works" className="py-32 bg-[#0c0c0f] border-t border-white/[0.06] relative">
      <div className="max-w-7xl mx-auto px-6 sm:px-8">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-xs font-mono text-blue-400 mb-4">
            <Sparkles className="w-3.5 h-3.5" />
            ZERO-FRICTION DATA PIPELINE
          </div>
          <h2 className="text-3xl sm:text-5xl font-bold tracking-tight text-white font-sans">
            How BizPilot AI Works in{' '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-indigo-300 to-purple-400">
              6 Simple Steps.
            </span>
          </h2>
          <p className="mt-4 text-zinc-400 text-base leading-relaxed">
            No complex setup required. Connect your existing accounting files or database and start receiving actionable intelligence in under 5 minutes.
          </p>
        </div>

        {/* Horizontal Visual Pipeline Timeline */}
        <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-6 mb-12">
          {pipelineSteps.map((item, idx) => {
            const IconComp = item.icon;
            const isCurrent = activePipelineStep === idx;
            return (
              <div
                key={item.step}
                onClick={() => setActivePipelineStep(idx)}
                className={`p-6 rounded-[20px] border transition-all duration-200 cursor-pointer relative ${
                  isCurrent
                    ? 'bg-zinc-900 border-blue-500/60 shadow-[0_0_20px_rgba(59,130,246,0.2)]'
                    : 'bg-[#121215]/80 border-white/[0.06] hover:bg-zinc-900/60'
                }`}
              >
                <div className="flex items-center justify-between mb-4">
                  <span className="text-xs font-mono font-bold text-zinc-500">{item.step}</span>
                  <div className={`p-2.5 rounded-xl ${isCurrent ? 'bg-blue-500/20 text-blue-400' : 'bg-zinc-800 text-zinc-400'}`}>
                    <IconComp className="w-4 h-4" />
                  </div>
                </div>

                <h4 className="text-sm font-bold text-white mb-2 font-sans line-clamp-1">{item.title}</h4>
                <p className="text-xs text-zinc-400 leading-relaxed line-clamp-2 font-normal">
                  {item.detail}
                </p>
              </div>
            );
          })}
        </div>

        {/* Active Step Live Code & Console Preview */}
        <div className="max-w-4xl mx-auto bg-[#09090b] border border-white/10 rounded-[20px] p-8 shadow-2xl">
          <div className="flex items-center justify-between pb-4 border-b border-white/10 mb-6">
            <div className="flex items-center gap-3">
              <span className="px-3 py-1 text-xs font-mono font-bold text-blue-400 bg-blue-500/10 border border-blue-500/20 rounded-md">
                PIPELINE NODE {pipelineSteps[activePipelineStep].step}
              </span>
              <span className="text-base font-semibold text-white font-sans">
                {pipelineSteps[activePipelineStep].title}
              </span>
            </div>
            <span className="text-xs font-mono text-emerald-400 flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
              PIPELINE ACTIVE
            </span>
          </div>

          <div className="p-5 rounded-xl bg-[#040406] border border-white/10 font-mono text-xs text-blue-300">
            <span className="text-zinc-500">// Real-time pipeline log</span>
            <div className="mt-1 text-zinc-200">{pipelineSteps[activePipelineStep].sampleData}</div>
          </div>

          <div className="mt-8 flex items-center justify-between">
            <p className="text-xs text-zinc-400">
              Click any node above to inspect pipeline transformation stages.
            </p>
            <button
              onClick={onGetStarted}
              className="h-12 px-6 text-xs font-semibold text-white bg-blue-600 hover:bg-blue-500 rounded-xl transition-colors flex items-center gap-2 cursor-pointer"
            >
              Start Free Integration
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
    </section>
  );
}
